server:
  port: 8080
  servlet:
    context-path: "/ufps/academic-friends-api"
spring:
  application:
    name: "academic-friends-api"
  devtools:
    add-properties: false
  profiles:
    active: "${env}"
  datasource:
    url: "${datasource_url}"
    username: "${datasource_username}"
    password: "${datasource_password}"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "update"
      show-sql: true
      format-sql: true
#  sql:
#    init:
#      mode: "always"
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  aws:
    s3:
      bucketName: "test"
      region: "us-east-1"
      endpoint: "https://s3.localhost.localstack.cloud:4566"
