AWSTemplateFormatVersion: "2010-09-09"

Description: "Infrastructure for the academic friends project"

Parameters:
  UserName:
    Type: String
    MinLength: 6
    MaxLength: 20
    Description: New account username
  UserPassword:
    NoEcho: "true"
    Type: String
    Description: New account password
    MinLength: 8
    MaxLength: 20

Resources:
  AdminGroup:
    Type: AWS::IAM::Group
  AdminPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AdminPolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: [ "*" ]
          Resource: "*"
      Groups: [ !Ref "AdminGroup" ]
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile:
        Password: !Ref UserPassword
      Groups: [ !Ref AdminGroup ]
  Keys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref "User"

Outputs:
  AccessKey:
    Value: !Ref "Keys"
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [ Keys, SecretAccessKey ]
    Description: AWSSecretAccessKey of new user
