version: '3'
services:

  af-back:
    image: s8vega/af-image
    ports:
    - "1800:8080"
    environment:
      datasource_password: ${DATASOURCE_PASSWORD}
      datasource_url: ${DATASOURCE_URL}
      datasource_username: ${DATASOURCE_USERNAME}
      env: ${ENV}
      secret_key: ${SECRET_KEY}

  af-front:
    image: s8vega/academicfriendsfront
    ports:
    - "1802:80"
    environment:
      API_URL: http://${API_HOST}/ufps/academic-friends-api